Welcome adapt
Gewaer/mobile-canvas pull request #49
Opened 2019-10-01 20:05 UTC by enmanuel-mctekk

2019-10-01 20:15 UTC, sperezm97 requested changes

2019-10-01 20:15 UTC, sperezm97 commented on src/screens/welcome/styled-components.ts
> +import styled from 'styled-components';
Tienes que hacer el los componentes globales y despúes heredar a los components por screen, si es necesario. Si le hacemos por cada pantalla, habra mucho código repetido innecesariamente.

2019-10-01 20:15 UTC, sperezm97 commented on src/screens/welcome/types.ts
> +  entries: object[]
para `entries` se necesita declarar la interface con el array de objects definido. Creo que es mejor colocar un type diferente, como: 'carrouselSlides' o 'slides'.

2019-10-02 14:02 UTC, alexup19 approved these changes

2019-10-02 17:32 UTC, merged